/**
 * Commandes de pizzas
 * Ceci est un exemple de l'api de commande des pizzas
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Commande {
    name?: string;
    adress?: string;
    pizzas?: Array<number>;
}
